#!/bin/sh

#PBS -l walltime=01:00:00
#PBS -l nodes=1:ppn=1
#PBS -l mem=20GB
#PBS -e /home/laine/PROJECTS_IO/SIMULATION/LOG/MAKE_PHANTOM/$dname.err
#PBS -o /home/laine/PROJECTS_IO/SIMULATION/LOG/MAKE_PHANTOM/$dname.out
#PBS -m ae
#PBS -M laine@creatis.insa-lyon.fr

# --- RUN THE SCRIPT
cd /misc/raid/home/laine/REPOSITORIES/CCA_DL_TOOLS/SIMULATION/mtl_cores

echo $pfolder
echo $dname
echo $pres
echo $pparam
echo $info

process="matlab -r fct_run_mk_phantom('$pfolder','$dname','$pres','$pparam','$info')"

echo $process
$process
