#!/bin/bash

#PBS -t 1-128
#PBS -l walltime=01:30:00
#PBS -l nodes=1:ppn=1
#PBS -l mem=15GB
#PBS -e /home/laine/PROJECTS_IO/SIMULATION/LOG/SIMULATION/${log_name}.err
#PBS -o /home/laine/PROJECTS_IO/SIMULATION/LOG/SIMULATION/${log_name}.out
#PBS -m ae

# --- RUN THE SCRIPT
cd /misc/raid/home/laine/REPOSITORIES/CCA_DL_TOOLS/SIMULATION/mtl_cores
instruction="matlab -r fct_run_wave_propagation('${path_param}','${path_phantom}',${PBS_ARRAYID})"
$instruction
