#!/bin/sh

#PBS -l walltime=20:00:00
#PBS -l nodes=4:ppn=2:gpus=1 -q gpu
#PBS -l mem=24GB
#PBS -m ae
#PBS -e $log_name.err
#PBS -o $log_name.out
#PBS -N $log_name
#PBS -M laine@creatis.insa-lyon.fr

source ~/anaconda3/etc/profile.d/conda.sh
conda activate pytorch

# package_core the script
WD=/home/laine/REPOSITORIES/CCA_DL_TOOLS/GANPostProcessing
cd $WD
PYTHONPATH=$WD python package_core/run_train_evaluate_model.py -param $param
